version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka
      - spark
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark:
    image: bitnami/spark:3
    ports:
      - "4040:4040"
    environment:
      SPARK_MASTER_URL: spark://spark:7077
      SPARK_JAVA_OPTS: --add-exports java.base/sun.nio.ch=ALL-UNNAMED
    depends_on:
      - kafka